services:
  score-service:
    image: openjdk:22-jdk-oracle
    container_name: scoreimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    env_file:
      - .env
    depends_on:
      - score-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/ScoreService-v1.0.7.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  score-db:
    image: mongo:latest
    container_name: scoredb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_score:/etc/mongo
      - mongo_score_data:/data/db
      - mongo_score_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:
    name: greenspot-net

volumes:
  mongo_score:
  mongo_score_data:
  mongo_score_config:
